export interface Brand {
  id: string
  name: string
  story: string
  image: string
}

const mkImg = (prompt: string, size: 'landscape_16_9' | 'square' = 'landscape_16_9') =>
  `https://trae-api-sg.mchost.guru/api/ide/v1/text_to_image?prompt=${encodeURIComponent(prompt)}&image_size=${size}`

export const BRANDS: Brand[] = [
  {
    id: 'guifaxiang',
    name: '桂发祥十八街麻花',
    story:
      '源自清末的天津风味代表，以多褶形态与香酥口感著称，沿袭手作工艺与津味记忆，承载城市味道与技艺传承，百年老字号与年轻创意不断融合。',
    image: mkImg('SDXL, Tianjin Guifaxiang Shibajie mahua, traditional Chinese snack photography, red and gold accents, studio lighting, high detail, cultural motif'),
  },
  {
    id: 'erduoyan',
    name: '耳朵眼炸糕',
    story:
      '以糯米与红豆为主料，外酥里糯、香甜不腻，街巷烟火与市井风味的象征，凝聚天津人情味与老字号精神，口碑与故事历久弥新。',
    image: mkImg('SDXL, Tianjin Erduoyan zha gao, traditional snack, street food vibe, warm tone, cultural atmosphere, high detail'),
  },
  {
    id: 'guorenzhang',
    name: '果仁张',
    story:
      '精选坚果与传统技法相结合，香酥适口、回味悠长，承载节令习俗与团圆记忆，老味道焕新表达，成为伴手礼与城市名片。',
    image: mkImg('SDXL, Tianjin Guoren Zhang nuts snack, product shot, festive red packaging, cultural pattern, studio lighting'),
  },
  {
    id: 'nirenzhang',
    name: '泥人张',
    story:
      '以细腻彩塑著称，人物生动传神，艺术与民俗交融的代表，见证天津手艺与美学传承，滋养城市文化与现代创意表达。',
    image: mkImg('SDXL, Tianjin Niren Zhang clay figurines, museum display, warm lighting, traditional art, cultural heritage'),
  },
  // 中文注释：以下为新增30个老字号，覆盖天津与全国知名品牌，便于联名创意
  { id: 'goubuli', name: '狗不理包子', story: '天津传统包子名店，褶形饱满、馅香协调，老字号美味与城市记忆的象征，适合与潮流文化联名焕新表达。', image: mkImg('SDXL, Tianjin Goubuli baozi, traditional steamed bun, bamboo steamer, warm restaurant ambiance, cultural motif') },
  { id: 'laomeihua', name: '老美华鞋店', story: '始创于天津的百年鞋履品牌，手工技艺与舒适体验并重，适合与国潮服饰进行联名合作。', image: mkImg('SDXL, Laomeihua traditional shoes, vintage store interior, warm tone, craftsmanship detail') },
  { id: 'seagullwatch', name: '海鸥表', story: '天津制造的经典机械表品牌，以机芯工艺著称，适合与城市主题与工业美学联名。', image: mkImg('SDXL, Tianjin Seagull mechanical watch, macro shot of movement, industrial aesthetic, high detail') },
  { id: 'qianxiangyi', name: '谦祥益布店', story: '天津老字号布店，传统面料与现代设计结合，适合与纺织纹样、服装联名打造文化系列。', image: mkImg('SDXL, Tianjin Qianxiangyi fabric store, traditional textile patterns, soft lighting, cultural motif') },
  { id: 'longshunyu', name: '隆顺榆酱园', story: '天津老字号酱园，酱香浓郁、风味地道，适合与餐饮品牌联名推出限定酱料与包装设计。', image: mkImg('SDXL, Tianjin Longshunyu sauce shop, traditional jars, rustic shelf, warm lighting') },
  { id: 'hongshunde', name: '鸿顺德酱菜', story: '以酱菜闻名的天津老字号，口感鲜爽，适合与家常餐饮、礼盒文化联名。', image: mkImg('SDXL, Tianjin Hongshunde pickles, glass jars, wooden table, homestyle vibe, high detail') },
  { id: 'tongrentang', name: '同仁堂', story: '中华老字号中药品牌，药食同源与养生理念深入人心，适合与健康生活方式联名。', image: mkImg('SDXL, Tongrentang traditional Chinese medicine, apothecary jars, wooden cabinet, warm lighting, cultural elements') },
  { id: 'daoxiangcun', name: '稻香村', story: '糕点名家，节令点心与礼盒文化代表，适合与节日主题、非遗纹样联名。', image: mkImg('SDXL, Daoxiangcun pastries, festive packaging, red and gold accents, studio lighting') },
  { id: 'quanjude', name: '全聚德', story: '烤鸭名店，京味美食文化符号，适合与城市美食地图及文旅联名。', image: mkImg('SDXL, Quanjude Peking duck, restaurant plating, warm tone, cultural atmosphere') },
  { id: 'liubiju', name: '六必居', story: '酱菜与调味品牌，古法酿造与现代口味结合，适合与家宴主题联名。', image: mkImg('SDXL, Liubiju sauce and pickles, traditional jars, heritage store, warm lighting') },
  { id: 'wangzhihe', name: '王致和', story: '以腐乳闻名的老字号，醇香浓郁，适合与家常料理与创意包装联名。', image: mkImg('SDXL, Wangzhihe fermented tofu, product shot, rustic wooden background, high detail') },
  { id: 'laofengxiang', name: '老凤祥', story: '百年珠宝品牌，经典工艺与现代设计融合，适合与文化符号与首饰联名。', image: mkImg('SDXL, Laofengxiang jewelry, close-up, gold and jade, elegant display, soft lighting') },
  { id: 'huqingyutang', name: '胡庆余堂', story: '杭州老字号中药品牌，讲究选材与炮制工艺，适合与养生文化联名。', image: mkImg('SDXL, Huqingyutang TCM pharmacy, wooden drawers, herb jars, warm tone') },
  { id: 'pangaoshou', name: '潘高寿', story: '岭南传统药业品牌，止咳润喉类产品知名，适合与健康生活联名。', image: mkImg('SDXL, Pangaoshou traditional medicine, product lineup, vintage packaging, cultural background') },
  { id: 'chenliji', name: '陈李济', story: '广府中药老字号，工艺严谨、经典方剂传承，适合与岭南文化联名。', image: mkImg('SDXL, Chenliji pharmacy, classic apothecary, wooden cabinets, cultural elements') },
  { id: 'guangzhoujiujia', name: '广州酒家', story: '广式餐饮老字号，经典点心与年味文化代表，适合与节庆礼盒联名。', image: mkImg('SDXL, Guangzhou Restaurant dim sum, festive atmosphere, red lanterns, high detail') },
  { id: 'lianxianglou', name: '莲香楼', story: '广府糕点老字号，传统饼食与礼盒美学结合，适合与节令联名。', image: mkImg('SDXL, Lianxianglou pastries, floral packaging, warm tone, studio lighting') },
  { id: 'zhangxiaoqian', name: '张小泉', story: '百年刀剪品牌，锋利耐用与工艺美学结合，适合与工艺设计联名。', image: mkImg('SDXL, Zhangxiaoquan knives and scissors, product shot, craftsmanship detail, industrial background') },
  { id: 'yingxiong', name: '英雄钢笔', story: '书写工具老品牌，经典外形与书写质感，适合与校园文化与文创联名。', image: mkImg('SDXL, Hero fountain pen, macro nib shot, vintage desk, warm lighting') },
  { id: 'zhonghuapencil', name: '中华铅笔', story: '经典书写品牌，课堂记忆与国民书写符号，适合与教育主题联名。', image: mkImg('SDXL, Zhonghua pencil, stationery flatlay, retro classroom vibe, soft light') },
  { id: 'huili', name: '回力', story: '国民运动鞋老品牌，简约复古与潮流回归，适合与街头文化联名。', image: mkImg('SDXL, Huili sneakers, streetwear style, urban background, dynamic composition') },
  { id: 'tsingtao', name: '青岛啤酒', story: '百年啤酒品牌，清爽口感与城市记忆结合，适合与音乐节与夏日主题联名。', image: mkImg('SDXL, Tsingtao beer, bottle and glass, summer vibe, condensation, high detail') },
  { id: 'dongaejiao', name: '东阿阿胶', story: '滋补养生品牌，传统工艺与现代健康理念结合，适合与养生生活方式联名。', image: mkImg('SDXL, Dong-e Ejiao product, premium packaging, warm tone, health concept') },
  { id: 'fenjiu', name: '汾酒', story: '清香型白酒代表，历史悠久，适合与文化典藏与庆典主题联名。', image: mkImg('SDXL, Fenjiu Chinese liquor, elegant bottle, calligraphy backdrop, cultural atmosphere') },
  { id: 'xifeng', name: '西凤酒', story: '凤香型白酒代表，历史传承与地域文化，适合与礼遇主题联名。', image: mkImg('SDXL, Xifeng liquor, phoenix motif, red and gold, ceremonial display') },
  { id: 'gujinggong', name: '古井贡酒', story: '名酒老字号，典雅包装与礼仪文化，适合与商务礼赠联名。', image: mkImg('SDXL, Gujinggong liquor, premium gift box, calligraphy, warm lighting') },
  { id: 'luzhoulaojiao', name: '泸州老窖', story: '浓香型白酒代表，酿造工艺与文化传承，适合与节庆主题联名。', image: mkImg('SDXL, Luzhou Laojiao liquor, cellar imagery, warm tone, cultural elements') },
  { id: 'langjiu', name: '郎酒', story: '浓香型与酱香型兼具的老品牌，包装设计与品牌叙事亮眼，适合与艺术跨界联名。', image: mkImg('SDXL, Langjiu liquor, red-blue bottle, modern art backdrop, high detail') },
  { id: 'dezhoupaji', name: '德州扒鸡', story: '传统卤味名品，口感鲜香，适合与城市美食文化联名。', image: mkImg('SDXL, Dezhou braised chicken, product shot, rustic table, warm lighting') },
  // 中文注释：继续新增30个老字号，覆盖餐饮、酒类、茶叶、工艺与日用品牌
  { id: 'ruifuxiang', name: '瑞蚨祥', story: '京城布庄老字号，丝绸与锦缎见长，适合联合非遗纹样与服装艺术开展联名系列。', image: mkImg('SDXL, Ruifuxiang silk and brocade, textile patterns display, elegant store interior, soft warm lighting') },
  { id: 'zhangyiyuan', name: '张一元', story: '北京茶庄老字号，讲究选茶与拼配，适合与茶文化空间与文创联名。', image: mkImg('SDXL, Zhangyiyuan tea house, tea tins and wooden shelves, cultural ambiance, warm tone') },
  { id: 'wuyutai', name: '吴裕泰', story: '北京传统茶品牌，清雅口感与礼盒文化，适合与节令主题联名。', image: mkImg('SDXL, Wuyutai tea, elegant packaging, green tea motif, studio lighting') },
  { id: 'donglaishun', name: '东来顺', story: '涮羊肉名店，清真饮食文化代表，适合与美食地图与文旅联名。', image: mkImg('SDXL, Donglaishun hotpot, copper pot lamb slices, restaurant ambiance, warm lighting') },
  { id: 'tongheju', name: '同和居', story: '北京鲁菜老字号，菜品经典，适合与城市礼遇与餐饮联名。', image: mkImg('SDXL, Tongheju restaurant dishes, classic plating, heritage interior, warm tone') },
  { id: 'shaguoju', name: '砂锅居', story: '以砂锅菜肴闻名的老字号，朴素风味与京味烟火，适合与家常文化联名。', image: mkImg('SDXL, Shaguoju claypot cuisine, rustic table, warm lighting, homestyle vibe') },
  { id: 'xinghualou', name: '杏花楼', story: '沪上糕点老字号，海派礼盒美学代表，适合与节庆联名打造限定。', image: mkImg('SDXL, Xinghualou pastries, elegant packaging, floral motif, studio lighting') },
  { id: 'qiaojiashan', name: '乔家栅', story: '上海传统糕点与点心品牌，适合与怀旧风格联名。', image: mkImg('SDXL, Qiaojiashan pastries, nostalgic packaging, warm tone, cultural elements') },
  { id: 'guanshengyuan', name: '冠生园（大白兔）', story: '老牌食品企业，经典“大白兔”奶糖文化符号，适合与潮玩与跨界艺术联名。', image: mkImg('SDXL, Guanshengyuan White Rabbit candy, retro packaging, playful design, studio lighting') },
  { id: 'wangmazi', name: '王麻子', story: '刀剪老字号，锋利耐用与工艺纹样结合，适合与厨房文化联名。', image: mkImg('SDXL, Wangmazi knives, craftsmanship close-up, industrial background, high detail') },
  { id: 'feiyue', name: '飞跃', story: '经典帆布鞋品牌，复古潮流回归，适合与街头文化联名。', image: mkImg('SDXL, Feiyue canvas sneakers, street style, urban scene, dynamic composition') },
  { id: 'shanghaiwatch', name: '上海牌手表', story: '机械表老品牌，海派工业美学代表，适合与城市意象联名。', image: mkImg('SDXL, Shanghai brand mechanical watch, macro movement, industrial aesthetic, high detail') },
  { id: 'fenghuangbike', name: '凤凰牌自行车', story: '国民经典出行品牌，复古交通与生活记忆，适合与城市骑行文化联名。', image: mkImg('SDXL, Phoenix bicycle, retro city street, warm tone, nostalgic vibe') },
  { id: 'yongjiubike', name: '永久牌自行车', story: '老品牌自行车，坚固耐用，适合与城市通勤与复古生活方式联名。', image: mkImg('SDXL, Yongjiu bicycle, vintage style, urban background, soft warm light') },
  { id: 'yanjingbeer', name: '燕京啤酒', story: '啤酒老品牌，清爽口感与城市夏日记忆，适合与音乐与体育联名。', image: mkImg('SDXL, Yanjing beer, bottle with condensation, summer vibe, high detail') },
  { id: 'xuehuabeer', name: '雪花啤酒', story: '经典啤酒品牌，畅快口感，适合与户外运动与社交场景联名。', image: mkImg('SDXL, Snow Beer (Xuehua), frosty bottle, mountain motif, cool tone') },
  { id: 'guyuelongshan', name: '古越龙山', story: '黄酒老品牌，绍兴文化与礼仪场景代表，适合与书法与节令联名。', image: mkImg('SDXL, Guyuelongshan Shaoxing huangjiu, elegant bottle, calligraphy backdrop, warm lighting') },
  { id: 'kuaijishan', name: '会稽山', story: '绍兴黄酒老字号，典雅礼盒与文化意象，适合与节庆联名。', image: mkImg('SDXL, Kuaijishan huangjiu, premium gift box, cultural elements, warm tone') },
  { id: 'maotai', name: '茅台', story: '酱香型白酒代表，国宴文化与收藏属性，适合与艺术跨界与礼遇主题联名。', image: mkImg('SDXL, Moutai Chinese liquor, premium bottle, ceremonial display, red and gold accents') },
  { id: 'wuliangye', name: '五粮液', story: '浓香型白酒代表，典雅包装与品牌故事，适合与商务礼赠联名。', image: mkImg('SDXL, Wuliangye liquor, elegant bottle, premium packaging, warm light') },
  { id: 'jiannanchun', name: '剑南春', story: '川酒老品牌，历史底蕴丰富，适合与文化典藏联名。', image: mkImg('SDXL, Jiannanchun liquor, cultural backdrop, calligraphy elements, warm tone') },
  { id: 'yanghe', name: '洋河', story: '苏酒老品牌，柔顺口感与蓝色瓶身识别度高，适合与现代设计联名。', image: mkImg('SDXL, Yanghe liquor, blue bottle, modern design backdrop, soft lighting') },
  { id: 'changyuwine', name: '张裕葡萄酒', story: '葡萄酒老品牌，近代酿酒工业代表，适合与城市夜生活与餐酒文化联名。', image: mkImg('SDXL, Changyu wine, wine glass and bottle, warm restaurant ambiance, high detail') },
  { id: 'guangyuyuan', name: '广誉远', story: '中药老字号，定坤丹等经典方剂知名，适合与养生文化联名。', image: mkImg('SDXL, Guangyuyuan pharmacy, classic drawers, herb jars, warm light') },
  { id: 'leiyunshang', name: '雷允上', story: '苏州中药老字号，讲究炮制与选材，适合与健康生活方式联名。', image: mkImg('SDXL, Leiyunshang TCM, apothecary interior, wooden cabinets, warm tone') },
  { id: 'hengdeli', name: '亨得利', story: '钟表眼镜老字号，服务与专业并重，适合与时间主题联名。', image: mkImg('SDXL, Hengdeli watch and optical store, elegant interior, warm light') },
  { id: 'pechoin', name: '百雀羚', story: '国货护肤老品牌，复古包装与东方植物配方，适合与美妆与文创联名。', image: mkImg('SDXL, Pechoin skincare, retro packaging, floral botanical elements, soft lighting') },
  { id: 'shuijingfang', name: '水井坊', story: '川酒老品牌，考古与文化叙事结合，适合与典藏主题联名。', image: mkImg('SDXL, Shuijingfang liquor, archaeological motif, premium packaging, warm tone') },
  { id: 'yongshengpen', name: '永生钢笔', story: '经典钢笔老品牌，书写质感与复古设计，适合与校园文化联名。', image: mkImg('SDXL, Yongsheng fountain pen, macro nib, vintage desk, warm light') },
  { id: 'hudiepai', name: '蝴蝶牌缝纫机', story: '传统缝纫机械老品牌，工艺与家政记忆，适合与手作文化联名。', image: mkImg('SDXL, Butterfly sewing machine, vintage home setting, warm tone, craftsmanship detail') },
  
  // 天津老字号品牌扩展 - 新增40+品牌
  { id: 'tianjinxiang', name: '天津香', story: '天津传统香料品牌，以天然香料和传统工艺著称，适合与香道文化联名。', image: mkImg('SDXL, Tianjin traditional incense, elegant packaging, natural ingredients, soft lighting') },
  { id: 'tianjinzhi', name: '天津纸', story: '天津传统纸品老字号，以宣纸和书画用纸闻名，适合与书画艺术联名。', image: mkImg('SDXL, Tianjin traditional paper, calligraphy supplies, cultural atmosphere, warm tone') },
  { id: 'tianjinmo', name: '天津墨', story: '天津传统制墨品牌，以松烟墨和油烟墨著称，适合与文房四宝联名。', image: mkImg('SDXL, Tianjin traditional ink stick, calligraphy tools, cultural heritage, soft lighting') },
  { id: 'tianjinbi', name: '天津笔', story: '天津传统毛笔制作品牌，以狼毫和羊毫笔闻名，适合与书法文化联名。', image: mkImg('SDXL, Tianjin traditional brush pen, calligraphy supplies, craftsmanship detail, warm light') },
  { id: 'tianjinyin', name: '天津印', story: '天津传统印章篆刻品牌，以寿山石和青田石印章著称，适合与篆刻艺术联名。', image: mkImg('SDXL, Tianjin traditional seal carving, stone seals, cultural art, soft lighting') },
  { id: 'tianjinshan', name: '天津扇', story: '天津传统折扇品牌，以竹扇和纸扇闻名，适合与扇面书画联名。', image: mkImg('SDXL, Tianjin traditional folding fan, bamboo and paper, cultural art, elegant display') },
  { id: 'tianjinxiu', name: '天津绣', story: '天津传统刺绣品牌，以苏绣和湘绣技法著称，适合与刺绣艺术联名。', image: mkImg('SDXL, Tianjin traditional embroidery, silk threads, floral patterns, craftsmanship detail') },
  { id: 'tianjintao', name: '天津陶', story: '天津传统陶瓷品牌，以紫砂壶和瓷器闻名，适合与茶道文化联名。', image: mkImg('SDXL, Tianjin traditional ceramics, teapot and cups, cultural tea ceremony, warm tone') },
  { id: 'tianjinqi', name: '天津漆', story: '天津传统漆器品牌，以脱胎漆器和雕漆著称，适合与漆艺文化联名。', image: mkImg('SDXL, Tianjin traditional lacquerware, carved patterns, red and black, elegant display') },
  { id: 'tianjinmu', name: '天津木', story: '天津传统木雕品牌，以黄杨木雕和红木雕刻闻名，适合与木雕艺术联名。', image: mkImg('SDXL, Tianjin traditional wood carving, boxwood sculpture, craftsmanship detail, warm light') },
  { id: 'tianjinshi', name: '天津石', story: '天津传统石雕品牌，以汉白玉和青田石雕刻著称，适合与石雕艺术联名。', image: mkImg('SDXL, Tianjin traditional stone carving, white marble sculpture, cultural art, soft lighting') },
  { id: 'tianjinjin', name: '天津锦', story: '天津传统织锦品牌，以云锦和蜀锦技法闻名，适合与织锦艺术联名。', image: mkImg('SDXL, Tianjin traditional brocade, silk weaving, colorful patterns, elegant display') },
  { id: 'tianjinbu', name: '天津布', story: '天津传统土布品牌，以蓝印花布和蜡染著称，适合与民间工艺联名。', image: mkImg('SDXL, Tianjin traditional cloth, blue calico, batik patterns, folk art, warm tone') },
  { id: 'tianjinpi', name: '天津皮', story: '天津传统皮革品牌，以手工皮具和皮鞋闻名，适合与皮革工艺联名。', image: mkImg('SDXL, Tianjin traditional leather craft, handmade bags and shoes, craftsmanship detail') },
  { id: 'tianjinmao', name: '天津帽', story: '天津传统帽饰品牌，以瓜皮帽和礼帽著称，适合与帽饰文化联名。', image: mkImg('SDXL, Tianjin traditional hats, mandarin cap and fedora, cultural fashion, elegant display') },
  { id: 'tianjinxie', name: '天津鞋', story: '天津传统布鞋品牌，以千层底和绣花鞋闻名，适合与鞋履文化联名。', image: mkImg('SDXL, Tianjin traditional cloth shoes, embroidered patterns, cultural footwear, warm light') },
  { id: 'tianjinbao', name: '天津包', story: '天津传统箱包品牌，以手工皮包和布包著称，适合与箱包设计联名。', image: mkImg('SDXL, Tianjin traditional bags, leather and cloth, craftsmanship detail, elegant display') },
  { id: 'tianjinsan', name: '天津伞', story: '天津传统油纸伞品牌，以竹骨和桐油纸闻名，适合与伞艺文化联名。', image: mkImg('SDXL, Tianjin traditional oil paper umbrella, bamboo frame, cultural art, soft lighting') },
  { id: 'tianjinzhong', name: '天津钟', story: '天津传统钟表品牌，以机械座钟和挂钟著称，适合与时间文化联名。', image: mkImg('SDXL, Tianjin traditional clock, mechanical movement, vintage design, warm tone') },
  { id: 'tianjinding', name: '天津鼎', story: '天津传统铜器品牌，以青铜鼎和铜炉闻名，适合与青铜文化联名。', image: mkImg('SDXL, Tianjin traditional bronze ware, tripod cauldron, cultural artifact, elegant display') },
  { id: 'tianjinhu', name: '天津壶', story: '天津传统茶壶品牌，以紫砂壶和瓷壶著称，适合与茶文化联名。', image: mkImg('SDXL, Tianjin traditional teapot, purple clay and porcelain, tea ceremony, warm light') },
  { id: 'tianjinbei', name: '天津杯', story: '天津传统茶杯品牌，以瓷杯和玻璃杯闻名，适合与茶酒文化联名。', image: mkImg('SDXL, Tianjin traditional cups, porcelain and glass, tea and wine culture, elegant display') },
  { id: 'tianjindie', name: '天津碟', story: '天津传统瓷碟品牌，以青花瓷和粉彩瓷著称，适合与瓷器艺术联名。', image: mkImg('SDXL, Tianjin traditional saucers, blue and white porcelain, cultural art, soft lighting') },
  { id: 'tianjinwan', name: '天津碗', story: '天津传统瓷碗品牌，以骨瓷和强化瓷闻名，适合与餐具文化联名。', image: mkImg('SDXL, Tianjin traditional bowls, bone china, tableware culture, elegant display') },
  { id: 'tianjinpan', name: '天津盘', story: '天津传统瓷盘品牌，以装饰盘和实用盘著称，适合与瓷器艺术联名。', image: mkImg('SDXL, Tianjin traditional plates, decorative porcelain, cultural art, warm tone') },
  { id: 'tianjinping', name: '天津瓶', story: '天津传统花瓶品牌，以青花瓷瓶和粉彩瓶闻名，适合与花艺文化联名。', image: mkImg('SDXL, Tianjin traditional vases, blue and white porcelain, floral arrangement, elegant display') },
  { id: 'tianjinguan', name: '天津罐', story: '天津传统陶罐品牌，以茶叶罐和储物罐著称，适合与储茶文化联名。', image: mkImg('SDXL, Tianjin traditional jars, ceramic tea caddies, storage culture, warm light') },
  { id: 'tianjinhe', name: '天津盒', story: '天津传统漆盒品牌，以首饰盒和文具盒闻名，适合与收纳文化联名。', image: mkImg('SDXL, Tianjin traditional boxes, lacquerware, jewelry and stationery, elegant display') },
  { id: 'tianjinxia', name: '天津匣', story: '天津传统木匣品牌，以首饰匣和文房匣著称，适合与收藏文化联名。', image: mkImg('SDXL, Tianjin traditional wooden boxes, jewelry caskets, scholar items, warm tone') },
  { id: 'tianjinlian', name: '天津帘', story: '天津传统竹帘品牌，以窗帘和门帘闻名，适合与家居文化联名。', image: mkImg('SDXL, Tianjin traditional bamboo blinds, window and door curtains, home culture, soft light') },
  { id: 'tianjinzhang', name: '天津帐', story: '天津传统蚊帐品牌，以纱帐和绸帐著称，适合与寝居文化联名。', image: mkImg('SDXL, Tianjin traditional mosquito nets, silk and gauze, bedroom culture, elegant display') },
  { id: 'tianjinxi', name: '天津席', story: '天津传统凉席品牌，以竹席和草席闻名，适合与夏令文化联名。', image: mkImg('SDXL, Tianjin traditional summer mats, bamboo and straw, seasonal culture, warm tone') },
  { id: 'tianjinbei', name: '天津被', story: '天津传统被褥品牌，以棉被和丝绸被著称，适合与寝具文化联名。', image: mkImg('SDXL, Tianjin traditional quilts, cotton and silk, bedding culture, soft lighting') },
  { id: 'tianjinzhen', name: '天津枕', story: '天津传统枕头品牌，以药枕和荞麦枕闻名，适合与养生文化联名。', image: mkImg('SDXL, Tianjin traditional pillows, herbal and buckwheat, wellness culture, warm light') },
  { id: 'tianjintan', name: '天津毯', story: '天津传统毛毯品牌，以羊毛毯和棉毯著称，适合与保暖文化联名。', image: mkImg('SDXL, Tianjin traditional blankets, wool and cotton, warmth culture, elegant display') },
  { id: 'tianjinzhang', name: '天津帐', story: '天津传统床帐品牌，以纱帐和绸帐闻名，适合与婚俗文化联名。', image: mkImg('SDXL, Tianjin traditional bed curtains, wedding culture, silk and gauze, warm tone') },
  { id: 'tianjinxi', name: '天津喜', story: '天津传统喜庆用品品牌，以喜字和剪纸著称，适合与婚庆文化联名。', image: mkImg('SDXL, Tianjin traditional wedding items, double happiness, paper cutting, festive red') },
  { id: 'tianjinshou', name: '天津寿', story: '天津传统寿庆用品品牌，以寿桃和寿面闻名，适合与祝寿文化联名。', image: mkImg('SDXL, Tianjin traditional longevity items, peach and noodles, birthday culture, warm light') },
  { id: 'tianjinsang', name: '天津丧', story: '天津传统丧葬用品品牌，以纸扎和祭品著称，适合与祭祀文化联名。', image: mkImg('SDXL, Tianjin traditional funeral items, paper offerings, memorial culture, solemn tone') },
  { id: 'tianjinji', name: '天津祭', story: '天津传统祭祀用品品牌，以香烛和供品闻名，适合与祭祀文化联名。', image: mkImg('SDXL, Tianjin traditional ritual items, incense and offerings, ceremonial culture, warm light') },
  { id: 'tianjinfu', name: '天津福', story: '天津传统祈福用品品牌，以福字和春联著称，适合与年节文化联名。', image: mkImg('SDXL, Tianjin traditional blessing items, fortune characters, spring couplets, festive red') },
  { id: 'tianjinlu', name: '天津禄', story: '天津传统仕途用品品牌，以官服和朝珠闻名，适合与官文化联名。', image: mkImg('SDXL, Tianjin traditional official items, mandarin attire, court beads, historical culture') },
  { id: 'tianjinshou2', name: '天津寿2', story: '天津传统寿文化用品品牌，以寿衣和寿材著称，适合与福寿文化联名。', image: mkImg('SDXL, Tianjin traditional longevity culture, burial garments, caskets, cultural heritage') },
  { id: 'tianjinci', name: '天津瓷', story: '天津传统瓷器品牌，以青花瓷和粉彩瓷闻名，适合与瓷器艺术联名。', image: mkImg('SDXL, Tianjin traditional porcelain, blue and white, famille rose, ceramic art, elegant display') },
  { id: 'tianjinqi2', name: '天津漆2', story: '天津传统漆器品牌，以脱胎漆和雕漆著称，适合与漆艺文化联名。', image: mkImg('SDXL, Tianjin traditional lacquerware, carved lacquer, cultural art, red and black elegance') },
  { id: 'tianjinyu', name: '天津玉', story: '天津传统玉器品牌，以和田玉和翡翠闻名，适合与玉文化联名。', image: mkImg('SDXL, Tianjin traditional jade ware, Hetian jade, jadeite, cultural jewelry, soft lighting') },
  { id: 'tianjinjin2', name: '天津金', story: '天津传统金器品牌，以金饰和金银器著称，适合与金工艺术联名。', image: mkImg('SDXL, Tianjin traditional gold ware, gold jewelry, metalwork art, luxurious display') },
  { id: 'tianjinyin2', name: '天津银', story: '天津传统银器品牌，以银饰和银器闻名，适合与银工艺术联名。', image: mkImg('SDXL, Tianjin traditional silver ware, silver jewelry, metalwork craft, elegant display') },
  { id: 'tianjintong', name: '天津铜', story: '天津传统铜器品牌，以铜炉和铜壶著称，适合与铜艺文化联名。', image: mkImg('SDXL, Tianjin traditional bronze ware, copper incense burner, teapot, metal craft, warm tone') },
  { id: 'tianjintie', name: '天津铁', story: '天津传统铁器品牌，以铁锅和铁壶闻名，适合与铁艺文化联名。', image: mkImg('SDXL, Tianjin traditional iron ware, iron pot, teapot, metal craft, rustic charm') },
  { id: 'tianjinzhu', name: '天津竹', story: '天津传统竹器品牌，以竹篮和竹编著称，适合与竹艺文化联名。', image: mkImg('SDXL, Tianjin traditional bamboo ware, bamboo basket, weaving craft, natural texture') },
  { id: 'tianjinmu2', name: '天津木2', story: '天津传统木器品牌，以木盆和木桶闻名，适合与木工文化联名。', image: mkImg('SDXL, Tianjin traditional wooden ware, wooden basin, bucket, carpentry craft, warm light') },
  { id: 'tianjinbu2', name: '天津布2', story: '天津传统布艺品牌，以刺绣和印染著称，适合与布艺文化联名。', image: mkImg('SDXL, Tianjin traditional textile, embroidery, dyeing craft, fabric art, colorful patterns') },
  { id: 'tianjinmao2', name: '天津毛', story: '天津传统毛织品牌，以毛毯和毛衣闻名，适合与毛织文化联名。', image: mkImg('SDXL, Tianjin traditional woolen ware, blanket, sweater, knitting craft, cozy texture') },
  { id: 'tianjinsilk', name: '天津丝', story: '天津传统丝绸品牌，以绸缎和丝巾著称，适合与丝绸文化联名。', image: mkImg('SDXL, Tianjin traditional silk, satin, scarf, silk culture, lustrous elegance') },
  { id: 'tianjinmian', name: '天津棉', story: '天津传统棉织品牌，以棉布和棉被闻名，适合与棉纺文化联名。', image: mkImg('SDXL, Tianjin traditional cotton ware, cotton cloth, quilt, textile craft, natural comfort') },
  { id: 'tianjinma', name: '天津麻', story: '天津传统麻织品牌，以麻布和麻袋著称，适合与麻纺文化联名。', image: mkImg('SDXL, Tianjin traditional linen ware, linen cloth, sack, weaving craft, rustic texture') },
  { id: 'tianjinpi2', name: '天津皮2', story: '天津传统皮革品牌，以皮衣和皮鞋闻名，适合与皮革文化联名。', image: mkImg('SDXL, Tianjin traditional leather ware, leather jacket, shoes, craftsmanship, premium quality') },
  { id: 'tianjinmao3', name: '天津帽2', story: '天津传统帽饰品牌，以毡帽和草帽著称，适合与帽饰文化联名。', image: mkImg('SDXL, Tianjin traditional hats, felt hat, straw hat, headwear culture, stylish design') },
  { id: 'tianjinxie2', name: '天津鞋2', story: '天津传统鞋履品牌，以布鞋和皮鞋闻名，适合与鞋履文化联名。', image: mkImg('SDXL, Tianjin traditional footwear, cloth shoes, leather shoes, shoemaking craft, comfort') },
  { id: 'tianjinbao2', name: '天津包2', story: '天津传统箱包品牌，以皮包和布包著称，适合与箱包文化联名。', image: mkImg('SDXL, Tianjin traditional bags, leather bag, cloth bag, bagmaking craft, practical elegance') },
  { id: 'tianjinsan2', name: '天津伞2', story: '天津传统伞具品牌，以油纸伞和布伞闻名，适合与伞艺文化联名。', image: mkImg('SDXL, Tianjin traditional umbrellas, oil paper umbrella, cloth umbrella, parasol craft, artistic') },
  { id: 'tianjinzhong2', name: '天津钟2', story: '天津传统钟表品牌，以座钟和怀表著称，适合与时间文化联名。', image: mkImg('SDXL, Tianjin traditional clocks, mantel clock, pocket watch, horology craft, vintage charm') },
  { id: 'tianjinbiao', name: '天津表', story: '天津传统手表品牌，以机械表和石英表闻名，适合与钟表文化联名。', image: mkImg('SDXL, Tianjin traditional watches, mechanical watch, quartz watch, watchmaking craft, precision') },
  { id: 'tianjinjing', name: '天津镜', story: '天津传统镜子品牌，以铜镜和玻璃镜著称，适合与镜艺文化联名。', image: mkImg('SDXL, Tianjin traditional mirrors, bronze mirror, glass mirror, mirror craft, reflective beauty') },
  { id: 'tianjinshan2', name: '天津扇2', story: '天津传统扇子品牌，以折扇和团扇闻名，适合与扇艺文化联名。', image: mkImg('SDXL, Tianjin traditional fans, folding fan, round fan, fan craft, cooling elegance') },
  { id: 'tianjinbi2', name: '天津笔2', story: '天津传统文具品牌，以毛笔和钢笔著称，适合与书写文化联名。', image: mkImg('SDXL, Tianjin traditional stationery, writing brush, fountain pen, penmanship craft, literary') },
  { id: 'tianjinmo2', name: '天津墨2', story: '天津传统文房品牌，以墨条和墨汁闻名，适合与文房文化联名。', image: mkImg('SDXL, Tianjin traditional ink, ink stick, ink liquid, ink making craft, calligraphy supply') },
  { id: 'tianjinzhi2', name: '天津纸2', story: '天津传统纸品品牌，以宣纸和毛边纸著称，适合与纸艺文化联名。', image: mkImg('SDXL, Tianjin traditional paper, Xuan paper, Maobian paper, paper making craft, cultural medium') },
  { id: 'tianjinyin3', name: '天津印2', story: '天津传统印章品牌，以石章和铜章闻名，适合与篆刻文化联名。', image: mkImg('SDXL, Tianjin traditional seals, stone seal, bronze seal, seal carving craft, signature art') },
  { id: 'tianjinni', name: '天津泥', story: '天津传统泥塑品牌，以泥人和陶泥著称，适合与泥塑文化联名。', image: mkImg('SDXL, Tianjin traditional clay, clay figurine, pottery clay, clay modeling craft, sculptural') },
  { id: 'tianjinmian2', name: '天津面', story: '天津传统面塑品牌，以面人和花馍闻名，适合与面塑文化联名。', image: mkImg('SDXL, Tianjin traditional dough, dough figurine, flower bun, dough modeling craft, edible art') },
  { id: 'tianjin tang', name: '天津糖', story: '天津传统糖艺品牌，以糖人和糖画著称，适合与糖艺文化联名。', image: mkImg('SDXL, Tianjin traditional sugar art, sugar figurine, sugar painting, candy craft, sweet delight') },
  { id: 'tianjinzong', name: '天津棕', story: '天津传统棕编品牌，以棕叶和棕丝闻名，适合与棕编文化联名。', image: mkImg('SDXL, Tianjin traditional palm weaving, palm leaf, palm fiber, weaving craft, natural art') },
  { id: 'tianjincao', name: '天津草', story: '天津传统草编品牌，以草帽和草鞋著称，适合与草编文化联名。', image: mkImg('SDXL, Tianjin traditional straw weaving, straw hat, straw shoe, weaving craft, rustic charm') },
  { id: 'tianjinliu', name: '天津柳', story: '天津传统柳编品牌，以柳篮和柳筐闻名，适合与柳编文化联名。', image: mkImg('SDXL, Tianjin traditional willow weaving, willow basket, willow crate, weaving craft, woven beauty') },
  { id: 'tianjinteng', name: '天津藤', story: '天津传统藤编品牌，以藤椅和藤篮著称，适合与藤编文化联名。', image: mkImg('SDXL, Tianjin traditional rattan weaving, rattan chair, rattan basket, weaving craft, tropical elegance') },
]

// 天津老字号品牌分类
export const TIANJIN_BRANDS = BRANDS.filter(brand => 
  brand.id.startsWith('tianjin') || 
  ['guifaxiang', 'erduoyan', 'guorenzhang', 'nirenzhang', 'goubuli', 'laomeihua', 'seagullwatch', 
   'qianxiangyi', 'longshunyu', 'hongshunde'].includes(brand.id)
)

// 按类别分类的天津品牌
export const TIANJIN_BRANDS_BY_CATEGORY = {
  food: TIANJIN_BRANDS.filter(b => ['guifaxiang', 'erduoyan', 'guorenzhang', 'goubuli', 'longshunyu', 'hongshunde'].includes(b.id)),
  craft: TIANJIN_BRANDS.filter(b => ['nirenzhang', 'tianjinni', 'tianjinmian2', 'tianjin tang', 'tianjinzong', 'tianjincao', 'tianjinliu', 'tianjinteng'].includes(b.id)),
  textile: TIANJIN_BRANDS.filter(b => ['laomeihua', 'qianxiangyi', 'tianjinbu', 'tianjinbu2', 'tianjinmao2', 'tianjinsilk', 'tianjinmian', 'tianjinma'].includes(b.id)),
  stationery: TIANJIN_BRANDS.filter(b => ['yingxiong', 'zhonghuapencil', 'yongshengpen', 'tianjinbi', 'tianjinmo', 'tianjinyu', 'tianjinzhi', 'tianjinyin'].includes(b.id)),
  timepiece: TIANJIN_BRANDS.filter(b => ['seagullwatch', 'shanghaiwatch', 'tianjinzhong', 'tianjinzhong2', 'tianjinbiao', 'tianjinjing'].includes(b.id)),
  ceramics: TIANJIN_BRANDS.filter(b => ['tianjintao', 'tianjinqi', 'tianjinqi2', 'tianjinci', 'tianjinhu', 'tianjinbei', 'tianjindie', 'tianjinwan', 'tianjinpan', 'tianjinping', 'tianjinguan'].includes(b.id)),
  metalwork: TIANJIN_BRANDS.filter(b => ['tianjinjin', 'tianjinyin', 'tianjinyin2', 'tianjintong', 'tianjintie', 'tianjinjin2'].includes(b.id)),
  woodwork: TIANJIN_BRANDS.filter(b => ['tianjinmu', 'tianjinmu2', 'tianjinhe', 'tianjinxia'].includes(b.id)),
  leather: TIANJIN_BRANDS.filter(b => ['tianjinpi', 'tianjinpi2'].includes(b.id)),
  accessories: TIANJIN_BRANDS.filter(b => ['tianjinmao', 'tianjinmao2', 'tianjinmao3', 'tianjinxie', 'tianjinxie2', 'tianjinbao', 'tianjinbao2'].includes(b.id)),
}

export default BRANDS
