COPY public.membership_benefits_config (id, level, name, description, features, limits, pricing, is_active, created_at, updated_at) FROM stdin;
40163c3c-a175-40ec-9069-7ad547ea13cb	free	免费会员	基础AI创作体验	[{"id": "ai_generation", "icon": "Wand2", "name": "AI生成次数", "value": "10次/天"}, {"id": "ai_model", "icon": "Zap", "name": "AI模型访问", "value": "基础模型"}, {"id": "image_generation", "icon": "Image", "name": "图像生成", "value": true}, {"id": "video_generation", "icon": "Video", "name": "视频生成", "value": false}, {"id": "audio_generation", "icon": "Music", "name": "音频生成", "value": false}, {"id": "text_generation", "icon": "FileText", "name": "文案生成", "value": true}, {"id": "templates", "icon": "Palette", "name": "模板库", "value": "基础模板"}, {"id": "layers", "icon": "Layers", "name": "图层编辑", "value": "基础功能"}, {"id": "export", "icon": "Download", "name": "导出功能", "value": "带水印"}, {"id": "storage", "icon": "Cloud", "name": "云存储空间", "value": "1GB"}, {"id": "priority", "icon": "Clock", "name": "优先处理", "value": false}, {"id": "commercial", "icon": "Shield", "name": "商业授权", "value": false}]	{"storageGB": 1, "watermark": true, "maxResolution": "1080p", "exportsPerMonth": 5, "aiGenerationsPerDay": 10}	{"monthly": {"price": 0, "period": "永久"}}	t	2026-02-11 07:49:54.803692+00	2026-02-11 07:49:54.803692+00
e94d3df9-1cc3-4e64-a309-efe59c61b574	premium	高级会员	解锁高级AI创作功能	[{"id": "ai_generation", "icon": "Wand2", "name": "AI生成次数", "value": "无限"}, {"id": "ai_model", "icon": "Zap", "name": "AI模型访问", "value": "高级模型"}, {"id": "image_generation", "icon": "Image", "name": "图像生成", "value": true}, {"id": "video_generation", "icon": "Video", "name": "视频生成", "value": true}, {"id": "audio_generation", "icon": "Music", "name": "音频生成", "value": true}, {"id": "text_generation", "icon": "FileText", "name": "文案生成", "value": true}, {"id": "templates", "icon": "Palette", "name": "模板库", "value": "专属模板库"}, {"id": "layers", "icon": "Layers", "name": "图层编辑", "value": "完整功能"}, {"id": "export", "icon": "Download", "name": "导出功能", "value": "高清无水印"}, {"id": "storage", "icon": "Cloud", "name": "云存储空间", "value": "50GB"}, {"id": "priority", "icon": "Clock", "name": "优先处理", "value": true}, {"id": "commercial", "icon": "Shield", "name": "商业授权", "value": false}]	{"storageGB": 50, "watermark": false, "maxResolution": "4K", "exportsPerMonth": 100, "aiGenerationsPerDay": null}	{"yearly": {"price": 899, "period": "年", "discount": "7.6折", "originalPrice": 1188}, "monthly": {"price": 99, "period": "月"}, "quarterly": {"price": 269, "period": "季度", "discount": "9折", "originalPrice": 297}}	t	2026-02-11 07:49:54.803692+00	2026-02-11 07:49:54.803692+00
d54d87f4-8381-4c50-8cbc-825cea9ca62c	vip	VIP会员	享受顶级AI创作体验	[{"id": "ai_generation", "icon": "Wand2", "name": "AI生成次数", "value": "无限"}, {"id": "ai_model", "icon": "Zap", "name": "AI模型访问", "value": "专属模型"}, {"id": "image_generation", "icon": "Image", "name": "图像生成", "value": true}, {"id": "video_generation", "icon": "Video", "name": "视频生成", "value": true}, {"id": "audio_generation", "icon": "Music", "name": "音频生成", "value": true}, {"id": "text_generation", "icon": "FileText", "name": "文案生成", "value": true}, {"id": "templates", "icon": "Palette", "name": "模板库", "value": "全部模板"}, {"id": "layers", "icon": "Layers", "name": "图层编辑", "value": "完整功能"}, {"id": "export", "icon": "Download", "name": "导出功能", "value": "超高清无水印"}, {"id": "storage", "icon": "Cloud", "name": "云存储空间", "value": "无限"}, {"id": "priority", "icon": "Clock", "name": "优先处理", "value": "最高优先级"}, {"id": "commercial", "icon": "Shield", "name": "商业授权", "value": true}]	{"storageGB": null, "watermark": false, "maxResolution": "8K", "exportsPerMonth": null, "aiGenerationsPerDay": null}	{"yearly": {"price": 1799, "period": "年", "discount": "7.5折", "originalPrice": 2388}, "monthly": {"price": 199, "period": "月"}, "quarterly": {"price": 539, "period": "季度", "discount": "9折", "originalPrice": 597}}	t	2026-02-11 07:49:54.803692+00	2026-02-11 07:49:54.803692+00
\.


--
-- Data for Name: membership_coupon_usage; Type: TABLE DATA; Schema: public; Owner: postgres
--
